sudo: required
services:
  - docker

before_install:
  - docker build -t sephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run sephengrider/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west2"
  app: "docker-react"
  env: "Dokcer-env"
  bucket_name: "elasticbeanstalk-us-west-2-892932423574857"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY